### ISSUE TITLE
PART_ColorStringTextBox does not refresh

### ISSUE THREAD

**Issue by Taldrit78** [dedpichto/ag.WPF.ColorPicker#6]
PART_ColorStringTextBox doesn't refresh under following circumstances:
Reproduction steps:
Define a Window with two different ColorPicker's.
Change the color of the first one.
Close this one with accept.
Open the second slider.
Change the color by using the PART_SpectrumSlider.
The TextBox doesn't refresh until you change the color by another kind then it works again.

**Comment by dedpichto** [comment]
Cannot reproduce the issue. See the attached video.
[https://1drv.ms/v/s!Am2fwVP7b6WF8QFR-7JNHs14rgnJ?e=BJbQVN](url)

**Comment by Taldrit78** [comment]
That is really strange, now I cannot reproduce it myself either...
Then I close this issue and if I am able to figure out HOW I did it, I will reopen it ;)
